name: build
on:
  push:
  pull_request_target:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: |
          echo "BUILD=$(date -u +%Y-%m-%d).$(git rev-parse --short=8 HEAD 2>/dev/null || echo 'snapshot')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: aaroncarson/eggcontractor:latest
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BUILD=${{ env.BUILD }}
            GIT_COMMIT=${{ github.sha }}

  ContractAggregator:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: misc/ContractAggregator
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Build
        run: |
          make
